CREATE SCHEMA IF NOT EXISTS APPSCHEMA;

CREATE TABLE IF NOT EXISTS "APPSCHEMA"."PERSON"
(
   ID VARCHAR(36) NOT NULL,
   CONSTRAINT PK_PERSONID PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS PK_PERSONID ON "APPSCHEMA"."PERSON"
(
  ID
);

